added precommit customized

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -1,129 +1,130 @@
-name: 'Snyk-iac'
-description: 'Find security issues in your Infrastructure as Code files.'
-author: 'ixxeL'
+---
+name: Snyk-iac
+description: Find security issues in your Infrastructure as Code files.
+author: ixxeL
 inputs:
   api-token:
-    description:  Your Snyk token. May be an user token or a service account.
+    description: Your Snyk token. May be an user token or a service account.
     required: true
   format:
-    description: 'Format result. [json, sarif]'
+    description: Format result. [json, sarif]
     required: false
     default: ''
   threshold:
-    description: 'Only report configuration issues with the provided severity level or higher [low,medium,high,critical]'
+    description: Only report configuration issues with the provided severity level or higher [low,medium,high,critical]
     required: false
-    default: 'low'
+    default: low
   depth:
     description: 'Indicate the maximum depth of sub-directories to search. default: unlimited'
     required: false
     default: ''
   org:
-    description: 'Specify the <ORG_NAME> to run Snyk commands tied to a specific organization. This will influence private tests limits.'
+    description: Specify the <ORG_NAME> to run Snyk commands tied to a specific organization. This will influence private tests limits.
     required: false
     default: ''
   output-json:
-    description: 'Redirect report to a JSON file'
+    description: Redirect report to a JSON file
     required: false
-    default: '""'    
+    default: '""'
   output-sarif:
-    description: 'Redirect report to a SARIF file'
+    description: Redirect report to a SARIF file
     required: false
     default: '""'
   exit-zero:
-    description: 'Force exit 0 code'
+    description: Force exit 0 code
     required: false
-    default: 'true'      
+    default: 'true'
   working-dir:
-    description: 'directory in which to find the Dockerfile'
+    description: directory in which to find the Dockerfile
     required: false
-    default: '.'
+    default: .
 
 runs:
-  using: "composite"
+  using: composite
   steps:
-    - id: snyk-iac
-      run: |
-        set +e
-        echo -e "${BLUE}[ STEP - IaC security scan ] > IaC code security scan with Snyk.${BLANK}"
-        echo -e "${CYAN}[ INFO ] > Snyk version.${BLANK}"
-        snyk --version
-        echo -e "${YELLOW}[ EXECUTING ] > Login with Snyk.${BLANK}"
-        snyk auth ${{ inputs.api-token }}
-        EXIT=$?
-        if [[ ${EXIT} = 0 ]]
-        then
-          echo -e "${GREEN}[ SUCCESS ] > Snyk auth succeeded.${BLANK}"
-        else
-          echo -e "${RED}[ FAIL ] > Snyk auth failed.${BLANK}"
-          exit ${EXIT}
-        fi
-        echo -e "${YELLOW}[ EXECUTING ] > Executing Snyk IaC test for org ${{ inputs.org }} on ${{ inputs.working-dir }} with threshold ${{ inputs.threshold }}.${BLANK}"
+  - id: snyk-iac
+    run: |
+      set +e
+      echo -e "${BLUE}[ STEP - IaC security scan ] > IaC code security scan with Snyk.${BLANK}"
+      echo -e "${CYAN}[ INFO ] > Snyk version.${BLANK}"
+      snyk --version
+      echo -e "${YELLOW}[ EXECUTING ] > Login with Snyk.${BLANK}"
+      snyk auth ${{ inputs.api-token }}
+      EXIT=$?
+      if [[ ${EXIT} = 0 ]]
+      then
+        echo -e "${GREEN}[ SUCCESS ] > Snyk auth succeeded.${BLANK}"
+      else
+        echo -e "${RED}[ FAIL ] > Snyk auth failed.${BLANK}"
+        exit ${EXIT}
+      fi
+      echo -e "${YELLOW}[ EXECUTING ] > Executing Snyk IaC test for org ${{ inputs.org }} on ${{ inputs.working-dir }} with threshold ${{ inputs.threshold }}.${BLANK}"
 
-        if [[ "${{ inputs.format }}" = "json" ]]
-        then
-          echo -e "${CYAN}[ INFO ] > Using JSON format.${BLANK}"
-          FORMAT="--json"
-        elif [[ "${{ inputs.format }}" = "sarif" ]]
-        then
-          echo -e "${CYAN}[ INFO ] > Using SARIF format.${BLANK}"
-          FORMAT="--sarif"
-        else
-          echo -e "${CYAN}[ INFO ] > Using DEFAULT format.${BLANK}"
-          FORMAT=""
-        fi
+      if [[ "${{ inputs.format }}" = "json" ]]
+      then
+        echo -e "${CYAN}[ INFO ] > Using JSON format.${BLANK}"
+        FORMAT="--json"
+      elif [[ "${{ inputs.format }}" = "sarif" ]]
+      then
+        echo -e "${CYAN}[ INFO ] > Using SARIF format.${BLANK}"
+        FORMAT="--sarif"
+      else
+        echo -e "${CYAN}[ INFO ] > Using DEFAULT format.${BLANK}"
+        FORMAT=""
+      fi
 
-        if [[ -n "${{ inputs.depth }}" ]]
-        then
-          echo -e "${CYAN}[ INFO ] > Using depth ${{ inputs.depth }}.${BLANK}"
-          DEPTH="--detection-depth=${{ inputs.depth }}"
-        else
-          DEPTH=""
-        fi
+      if [[ -n "${{ inputs.depth }}" ]]
+      then
+        echo -e "${CYAN}[ INFO ] > Using depth ${{ inputs.depth }}.${BLANK}"
+        DEPTH="--detection-depth=${{ inputs.depth }}"
+      else
+        DEPTH=""
+      fi
 
-        if [[ -n "${{ inputs.output-json }}" ]]
-        then
-          echo -e "${CYAN}[ INFO ] > output JSON file to ${{ inputs.output-json }}.${BLANK}"
-          OUTPUT="--json-file-output=${{ inputs.output-json }}"
-        elif [[ -n "${{ inputs.output-sarif }}" ]]
-        then
-          echo -e "${CYAN}[ INFO ] > output SARIF file to ${{ inputs.output-sarif }}.${BLANK}"
-          OUTPUT="--json-file-output=${{ inputs.output-sarif }}"
-        else
-          OUTPUT=""
-        fi
-  
-        if [[ -z "${FORMAT}" ]]
-        then
-          snyk iac test ${{ inputs.working-dir }} \
-                        --severity-threshold=${{ inputs.threshold }} \
-                        --org=${{ inputs.org }} \
-                        ${DEPTH} \
-                        ${OUTPUT} \
-                        ${FORMAT}
-        else
-          snyk iac test ${{ inputs.working-dir }} \
-                        --severity-threshold=${{ inputs.threshold }} \
-                        --org=${{ inputs.org }} \
-                        ${DEPTH} \
-                        ${OUTPUT} \
-                        ${FORMAT} | jq -C
-        fi
+      if [[ -n "${{ inputs.output-json }}" ]]
+      then
+        echo -e "${CYAN}[ INFO ] > output JSON file to ${{ inputs.output-json }}.${BLANK}"
+        OUTPUT="--json-file-output=${{ inputs.output-json }}"
+      elif [[ -n "${{ inputs.output-sarif }}" ]]
+      then
+        echo -e "${CYAN}[ INFO ] > output SARIF file to ${{ inputs.output-sarif }}.${BLANK}"
+        OUTPUT="--json-file-output=${{ inputs.output-sarif }}"
+      else
+        OUTPUT=""
+      fi
 
-        EXIT_CODE="${PIPESTATUS[0]}"
-        if [[ ${EXIT_CODE} -ne 0 && ${{ inputs.exit-zero }} != true ]]
-        then
-          echo -e "${RED}[ FAIL ] > Snyk IaC scan failed.${BLANK}"
-          exit ${EXIT_CODE}
-        else
-          echo -e "${GREEN}[ SUCCESS ] > Snyk IaC scan succeeded.${BLANK}"
-        fi
-      shell: bash
-      env:
-        RED: \033[1;31m
-        GREEN: \033[1;32m
-        YELLOW: \033[1;33m
-        BLUE: \033[1;34m
-        PURPLE: \033[1;35m
-        CYAN: \033[1;36m
-        BLANK: \033[0m
-        FORCE_COLOR: 3
+      if [[ -z "${FORMAT}" ]]
+      then
+        snyk iac test ${{ inputs.working-dir }} \
+                      --severity-threshold=${{ inputs.threshold }} \
+                      --org=${{ inputs.org }} \
+                      ${DEPTH} \
+                      ${OUTPUT} \
+                      ${FORMAT}
+      else
+        snyk iac test ${{ inputs.working-dir }} \
+                      --severity-threshold=${{ inputs.threshold }} \
+                      --org=${{ inputs.org }} \
+                      ${DEPTH} \
+                      ${OUTPUT} \
+                      ${FORMAT} | jq -C
+      fi
+
+      EXIT_CODE="${PIPESTATUS[0]}"
+      if [[ ${EXIT_CODE} -ne 0 && ${{ inputs.exit-zero }} != true ]]
+      then
+        echo -e "${RED}[ FAIL ] > Snyk IaC scan failed.${BLANK}"
+        exit ${EXIT_CODE}
+      else
+        echo -e "${GREEN}[ SUCCESS ] > Snyk IaC scan succeeded.${BLANK}"
+      fi
+    shell: bash
+    env:
+      RED: \033[1;31m
+      GREEN: \033[1;32m
+      YELLOW: \033[1;33m
+      BLUE: \033[1;34m
+      PURPLE: \033[1;35m
+      CYAN: \033[1;36m
+      BLANK: \033[0m
+      FORCE_COLOR: 3
